nifi_config:
  encrypPassword: aLfzjqudxvTQRoas5VDBsVTTO1sBOC7SNn7e8PEwF188pcRxNEKnVS3SzssaSY606HuIfgtLFt67VZVBpvMVw2aJjvkQHdT1H3MWfRce1ktiDgFjslXY0Dn/td6K24SYKvnhyifQ5aKNJBRbwOWsvXiBOHowCY0oXxJRJp/fO06ZjwmaNOKivvT79UVJwjxuFcycy7KH+TTO4DBodRLaIwowdQh/nVF8PhcTXIQjl5W//jWamH+Qu6AfzH+RX9wamS3If94EzVWFlYy9lQHIGbAkFMqhcUM1H68b1OmXyUEqPbZZUofcoDv6v0bN2yf7mUYdwwcJ/jX7wPZUjc3g5tEk5/cPuOme+5R7wEiUG20VvapDja8r+ky5gJb8irS1x8Dgafl5TPQjM7rXRgQ3vsHhZv4V9pMcsqMrtgWA7LVlz+VA6mxbnaolXjpDbFb/btbQ3U4CaBiQPnbSpD5awiKBezaXgWyUiuNS5NHcqMVpnK1lLTDiY9IMuKGukDaT1OLdprUkBxGIDaR3RxyS4wW8OmlXGKO03/HEJC5AmdCqtOJ8v6df6wv2E/F5VxM31O7LZ3tnQhi16UeBboyzibLr7NxyP6lTqJ866PR7GiC9+EVIP/imlrCfZ8KzDWFTETO6NgGsvI2WV3nubGPFLpM+j8oj5yMXq1LVD+Ziz4c=
  host: https://nifi.devdata.lmru.tech
  nifi_api: /nifi-api
  nifi_web: /nifi
  registry_api: /nifi-registry-api
  username: '60110912'
