nifi_config:
  encrypPassword: gwlhtD6WMqhsh00M/SDmay84D03oUPo7ccHt8b0e3aTAAEy/zBO6VgiEhamso5fZbzDzZfnxOft74UUQhLFv1A2/FRBBNhPSr3R2z7rj4yLeCrxvt/Z/TmgtWxP7SgY8zL3SlpHI0RkjOOiGEapmWKCDkk9B29d7Ug/i6wGrqn1qCDw4ST/yrKNFJexaP0Z/akY2jO9yvBR+VQ0oz91bMdmthPRL+KDEuDNtsPZJtHXATAWQBkUt/zox5bjn7NEMaYKlud4lyRLWlp/gZ3dw7SPJvlDJQvOF338/oWHIZuUSxHnx3GBrx0VTRzrzdy2PbkcYl4+OAvVG+ZwXsk6na8snc6UuHtz3J2DREbha8X2V4C9WSacCE4zqvXQ4s+cTYOVkX0KEQQnucmwhY3uEKV3LnxOZoA7PyVwWayZRShcjdNoV0ppzclHWwp6yQH0QN5XQz8tZyRib2sesw18jUnYZO8A74u2x5fp32AQICZH/ejNjj2F0MZ/NGzC2ybYWro1HB9uYdfRcOv/uGaGuZu7aG3V9Eb2wDt6Aw3V1nP7R50lfxMY51/IDve2d86tmg8By5kMYs0S7iVmNfKJjgZpE7AOMEyrxcQc36hEzO1NsMV6J3SpH1HQaXPXVmNCcvt0AXhzJHtD1w6fO8S855Zs2WrnyOmf/vqa/gLyKzNY=
  host: https://nifi.devdata.lmru.tech
  nifi_api: /nifi-api
  nifi_web: /nifi
  registry_api: /nifi-registry-api
  username: '60110912'
